"""
Type stubs for essentia._essentia (C++ extension).
"""

from typing import Any
import numpy as np
import numpy.typing as npt

class Algorithm:
    name: str
    def __init__(self, name: str) -> None: ...

class StreamingAlgorithm:
    name: str
    def __init__(self, name: str) -> None: ...

def version() -> str: ...
def version_git_sha() -> str: ...
def keys() -> list[str]: ...
def info(name: str) -> dict[str, Any]: ...
def reset() -> None: ...
