"""
Type stubs for essentia.standard algorithms.

Auto-generated -- 251 algorithms.
"""

from typing import Any, Tuple
import numpy.typing as npt
import numpy as np
from essentia._essentia import Algorithm
from essentia import Pool

class AfterMaxToBeforeMaxEnergyRatio(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, pitch: np.ndarray) -> float: ...

class AllPass(Algorithm):
    def __init__(self, bandwidth: float = 500, cutoffFrequency: float = 1500, order: int = 1, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class Audio2Midi(Algorithm):
    def __init__(self, applyTimeCompensation: bool = True, hopSize: int = 32, loudnessThreshold: float = -51, maxFrequency: float = 2300, midiBufferDuration: float = 0.05, minFrequency: float = 60, minNoteChangePeriod: float = 0.03, minOccurrenceRate: float = 0.5, minOffsetCheckPeriod: float = 0.2, minOnsetCheckPeriod: float = 0.075, pitchConfidenceThreshold: float = 0.25, sampleRate: int = 44100, transpositionAmount: int = 0, tuningFrequency: int = 440) -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[float, float, list[str], np.ndarray, np.ndarray]: ...

class Audio2Pitch(Algorithm):
    def __init__(self, frameSize: int = 1024, loudnessThreshold: float = -51, maxFrequency: float = 2300, minFrequency: float = 60, pitchAlgorithm: str = 'pitchyinfft', pitchConfidenceThreshold: float = 0.25, sampleRate: int = 44100, tolerance: float = 1, weighting: str = 'custom') -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[float, float, float, int]: ...

class AudioLoader(Algorithm):
    def __init__(self, audioStream: int = 0, computeMD5: bool = False, filename: str) -> None: ...
    def __call__(self) -> tuple[Any, float, int, str, int, str]: ...

class AudioOnsetsMarker(Algorithm):
    def __init__(self, onsets: np.ndarray = '[]', sampleRate: float = 44100, type: str = 'beep') -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class AudioWriter(Algorithm):
    def __init__(self, bitrate: int = 192, filename: str, format: str = 'wav', sampleRate: float = 44100) -> None: ...
    def __call__(self, audio: Any) -> None: ...

class AutoCorrelation(Algorithm):
    def __init__(self, frequencyDomainCompression: float = 0.5, generalized: bool = False, normalization: str = 'standard') -> None: ...
    def __call__(self, array: np.ndarray) -> np.ndarray: ...

class BFCC(Algorithm):
    def __init__(self, dctType: int = 2, highFrequencyBound: float = 11000, inputSize: int = 1025, liftering: int = 0, logType: str = 'dbamp', lowFrequencyBound: float = 0, normalize: str = 'unit_sum', numberBands: int = 40, numberCoefficients: int = 13, sampleRate: float = 44100, type: str = 'power', weighting: str = 'warping') -> None: ...
    def __call__(self, spectrum: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class BPF(Algorithm):
    def __init__(self, xPoints: np.ndarray = '[0', yPoints: np.ndarray = '[0') -> None: ...
    def __call__(self, x: float) -> float: ...

class BandPass(Algorithm):
    def __init__(self, bandwidth: float = 500, cutoffFrequency: float = 1500, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class BandReject(Algorithm):
    def __init__(self, bandwidth: float = 500, cutoffFrequency: float = 1500, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class BarkBands(Algorithm):
    def __init__(self, numberBands: int = 27, sampleRate: float = 44100) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> np.ndarray: ...

class BeatTrackerDegara(Algorithm):
    def __init__(self, maxTempo: int = 208, minTempo: int = 40) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class BeatTrackerMultiFeature(Algorithm):
    def __init__(self, maxTempo: int = 208, minTempo: int = 40) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[np.ndarray, float]: ...

class Beatogram(Algorithm):
    def __init__(self, size: int = 16) -> None: ...
    def __call__(self, loudness: np.ndarray, loudnessBandRatio: Any) -> Any: ...

class BeatsLoudness(Algorithm):
    def __init__(self, beatDuration: float = 0.05, beatWindowDuration: float = 0.1, beats: np.ndarray = '[]', frequencyBands: np.ndarray = '[20', sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[np.ndarray, Any]: ...

class BinaryOperator(Algorithm):
    def __init__(self, type: str = 'add') -> None: ...
    def __call__(self, array1: np.ndarray, array2: np.ndarray) -> np.ndarray: ...

class BinaryOperatorStream(Algorithm):
    def __init__(self, type: str = 'add') -> None: ...
    def __call__(self, array1: np.ndarray, array2: np.ndarray) -> np.ndarray: ...

class BpmHistogram(Algorithm):
    def __init__(self, bpm: float = 0, constantTempo: bool = False, frameRate: float = 86.1328, frameSize: float = 4, maxBpm: float = 560, maxPeaks: int = 50, minBpm: float = 30, overlap: int = 16, tempoChange: float = 5, weightByMagnitude: bool = True, windowType: str = 'hann', zeroPadding: int = 0) -> None: ...
    def __call__(self, novelty: np.ndarray) -> tuple[float, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...

class BpmHistogramDescriptors(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, bpmIntervals: np.ndarray) -> tuple[float, float, float, float, float, float, np.ndarray]: ...

class BpmRubato(Algorithm):
    def __init__(self, longRegionsPruningTime: float = 20, shortRegionsMergingTime: float = 4, tolerance: float = 0.08) -> None: ...
    def __call__(self, beats: np.ndarray) -> tuple[np.ndarray, np.ndarray, int]: ...

class CartesianToPolar(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, complex: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class CentralMoments(Algorithm):
    def __init__(self, mode: str = 'pdf', range: float = 1) -> None: ...
    def __call__(self, array: np.ndarray) -> np.ndarray: ...

class Centroid(Algorithm):
    def __init__(self, range: float = 1) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class ChordsDescriptors(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, chords: list[str], key: str, scale: str) -> tuple[np.ndarray, float, float, str, str]: ...

class ChordsDetection(Algorithm):
    def __init__(self, hopSize: int = 2048, sampleRate: float = 44100, windowSize: float = 2) -> None: ...
    def __call__(self, pcp: Any) -> tuple[list[str], np.ndarray]: ...

class ChordsDetectionBeats(Algorithm):
    def __init__(self, chromaPick: str = 'interbeat_median', hopSize: int = 2048, sampleRate: float = 44100) -> None: ...
    def __call__(self, pcp: Any, ticks: np.ndarray) -> tuple[list[str], np.ndarray]: ...

class ChromaCrossSimilarity(Algorithm):
    def __init__(self, binarizePercentile: float = 0.095, frameStackSize: int = 9, frameStackStride: int = 1, noti: int = 12, oti: bool = True, otiBinary: bool = False, streaming: bool = False) -> None: ...
    def __call__(self, queryFeature: Any, referenceFeature: Any) -> Any: ...

class Chromagram(Algorithm):
    def __init__(self, binsPerOctave: int = 12, minFrequency: float = 32.7, minimumKernelSize: int = 4, normalizeType: str = 'unit_max', numberBins: int = 84, sampleRate: float = 44100, scale: float = 1, threshold: float = 0.01, windowType: str = 'hann', zeroPhase: bool = True) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class Chromaprinter(Algorithm):
    def __init__(self, maxLength: float = 0, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> str: ...

class ClickDetector(Algorithm):
    def __init__(self, detectionThreshold: float = 30, frameSize: int = 512, hopSize: int = 256, order: int = 12, powerEstimationThreshold: int = 10, sampleRate: float = 44100, silenceThreshold: int = -50) -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class Clipper(Algorithm):
    def __init__(self, max: float = 1, min: float = -1) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class ConstantQ(Algorithm):
    def __init__(self, binsPerOctave: int = 12, minFrequency: float = 32.7, minimumKernelSize: int = 4, numberBins: int = 84, sampleRate: float = 44100, scale: float = 1, threshold: float = 0.01, windowType: str = 'hann', zeroPhase: bool = True) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class CoverSongSimilarity(Algorithm):
    def __init__(self, alignmentType: str = 'serra09', disExtension: float = 0.5, disOnset: float = 0.5, distanceType: str = 'asymmetric') -> None: ...
    def __call__(self, inputArray: Any) -> tuple[Any, float]: ...

class Crest(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class CrossCorrelation(Algorithm):
    def __init__(self, maxLag: int = 1, minLag: int = 0) -> None: ...
    def __call__(self, arrayX: np.ndarray, arrayY: np.ndarray) -> np.ndarray: ...

class CrossSimilarityMatrix(Algorithm):
    def __init__(self, binarize: bool = False, binarizePercentile: float = 0.095, frameStackSize: int = 1, frameStackStride: int = 1) -> None: ...
    def __call__(self, queryFeature: Any, referenceFeature: Any) -> Any: ...

class CubicSpline(Algorithm):
    def __init__(self, leftBoundaryFlag: int = 0, leftBoundaryValue: float = 0, rightBoundaryFlag: int = 0, rightBoundaryValue: float = 0, xPoints: np.ndarray = '[0', yPoints: np.ndarray = '[0') -> None: ...
    def __call__(self, x: float) -> tuple[float, float, float]: ...

class DCRemoval(Algorithm):
    def __init__(self, cutoffFrequency: float = 40, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class DCT(Algorithm):
    def __init__(self, dctType: int = 2, inputSize: int = 10, liftering: int = 0, outputSize: int = 10) -> None: ...
    def __call__(self, array: np.ndarray) -> np.ndarray: ...

class Danceability(Algorithm):
    def __init__(self, maxTau: float = 8800, minTau: float = 310, sampleRate: float = 44100, tauMultiplier: float = 1.1) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[float, np.ndarray]: ...

class Decrease(Algorithm):
    def __init__(self, range: float = 1) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class Derivative(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class DerivativeSFX(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, envelope: np.ndarray) -> tuple[float, float]: ...

class DiscontinuityDetector(Algorithm):
    def __init__(self, detectionThreshold: float = 8, energyThreshold: float = -60, frameSize: int = 512, hopSize: int = 256, kernelSize: int = 7, order: int = 3, silenceThreshold: int = -50, subFrameSize: int = 32) -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class Dissonance(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, frequencies: np.ndarray, magnitudes: np.ndarray) -> float: ...

class DistributionShape(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, centralMoments: np.ndarray) -> tuple[float, float, float]: ...

class Duration(Algorithm):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...

class DynamicComplexity(Algorithm):
    def __init__(self, frameSize: float = 0.2, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[float, float]: ...

class ERBBands(Algorithm):
    def __init__(self, highFrequencyBound: float = 22050, inputSize: int = 1025, lowFrequencyBound: float = 50, numberBands: int = 40, sampleRate: float = 44100, type: str = 'power', width: float = 1) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> np.ndarray: ...

class EasyLoader(Algorithm):
    def __init__(self, audioStream: int = 0, downmix: str = 'mix', endTime: float = 1e+06, filename: str, replayGain: float = -6, sampleRate: float = 44100, startTime: float = 0) -> None: ...
    def __call__(self) -> np.ndarray: ...

class EffectiveDuration(Algorithm):
    def __init__(self, sampleRate: float = 44100, thresholdRatio: float = 0.4) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...

class Energy(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class EnergyBand(Algorithm):
    def __init__(self, sampleRate: float = 44100, startCutoffFrequency: float = 0, stopCutoffFrequency: float = 100) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> float: ...

class EnergyBandRatio(Algorithm):
    def __init__(self, sampleRate: float = 44100, startFrequency: float = 0, stopFrequency: float = 100) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> float: ...

class Entropy(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class Envelope(Algorithm):
    def __init__(self, applyRectification: bool = True, attackTime: float = 10, releaseTime: float = 1500, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class EqloudLoader(Algorithm):
    def __init__(self, downmix: str = 'mix', endTime: float = 1e+06, filename: str, replayGain: float = -6, sampleRate: float = 44100, startTime: float = 0) -> None: ...
    def __call__(self) -> np.ndarray: ...

class EqualLoudness(Algorithm):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class Extractor(Algorithm):
    def __init__(self, dynamics: bool = True, dynamicsFrameSize: int = 88200, dynamicsHopSize: int = 44100, highLevel: bool = True, lowLevel: bool = True, lowLevelFrameSize: int = 2048, lowLevelHopSize: int = 1024, midLevel: bool = True, namespace: str = '“”', relativeIoi: bool = False, rhythm: bool = True, sampleRate: float = 44100, tonalFrameSize: int = 4096, tonalHopSize: int = 2048, tuning: bool = True) -> None: ...
    def __call__(self, audio: np.ndarray) -> Pool: ...

class FFT(Algorithm):
    def __init__(self, size: int = 1024) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class FFTC(Algorithm):
    def __init__(self, negativeFrequencies: bool = False, size: int = 1024) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class FadeDetection(Algorithm):
    def __init__(self, cutoffHigh: float = 0.85, cutoffLow: float = 0.2, frameRate: float = 4, minLength: float = 3) -> None: ...
    def __call__(self, rms: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class FalseStereoDetector(Algorithm):
    def __init__(self, correlationThreshold: float = 0.9995, silenceThreshold: int = -70) -> None: ...
    def __call__(self, frame: Any) -> tuple[int, float]: ...

class Flatness(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class FlatnessDB(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class FlatnessSFX(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, envelope: np.ndarray) -> float: ...

class Flux(Algorithm):
    def __init__(self, halfRectify: bool = False, norm: str = 'L2') -> None: ...
    def __call__(self, spectrum: np.ndarray) -> float: ...

class FrameBuffer(Algorithm):
    def __init__(self, bufferSize: int = 2048, zeroPadding: bool = True) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class FrameCutter(Algorithm):
    def __init__(self, frameSize: int = 1024, hopSize: int = 512, lastFrameToEndOfFile: bool = False, startFromZero: bool = False, validFrameThresholdRatio: float = 0) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class FrameToReal(Algorithm):
    def __init__(self, frameSize: int = 2048, hopSize: int = 128) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class FreesoundExtractor(Algorithm):
    def __init__(self, analysisSampleRate: float = 44100, endTime: float = 1e+06, gfccStats: list[str] = '[“mean”', highlevel: list[str], lowlevelFrameSize: int = 2048, lowlevelHopSize: int = 1024, lowlevelSilentFrames: str = 'noise', lowlevelStats: list[str] = '[“mean”', lowlevelWindowType: str = 'blackmanharris62', lowlevelZeroPadding: int = 0, mfccStats: list[str] = '[“mean”', profile: str, rhythmMaxTempo: int = 210, rhythmMethod: str = 'multifeature', rhythmMinTempo: int = 40, rhythmStats: list[str] = '[“mean”', startTime: float = 0, tonalFrameSize: int = 4096, tonalHopSize: int = 2048, tonalSilentFrames: str = 'noise', tonalStats: list[str] = '[“mean”', tonalWindowType: str = 'blackmanharris62', tonalZeroPadding: int = 0) -> None: ...
    def __call__(self, filename: str) -> tuple[Pool, Pool]: ...

class FrequencyBands(Algorithm):
    def __init__(self, frequencyBands: np.ndarray = '[0', sampleRate: float = 44100) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> np.ndarray: ...

class GFCC(Algorithm):
    def __init__(self, dctType: int = 2, highFrequencyBound: float = 22050, inputSize: int = 1025, logType: str = 'dbamp', lowFrequencyBound: float = 40, numberBands: int = 40, numberCoefficients: int = 13, sampleRate: float = 44100, silenceThreshold: float = 1e-10, type: str = 'power') -> None: ...
    def __call__(self, spectrum: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class GapsDetector(Algorithm):
    def __init__(self, attackTime: float = 0.05, frameSize: int = 2048, hopSize: int = 1024, kernelSize: int = 11, maximumTime: float = 3500, minimumTime: float = 10, postpowerTime: float = 40, prepowerThreshold: float = -30, prepowerTime: float = 40, releaseTime: float = 0.05, sampleRate: float = 44100, silenceThreshold: float = -50) -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class GeometricMean(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class HFC(Algorithm):
    def __init__(self, sampleRate: float = 44100, type: str = 'Masri') -> None: ...
    def __call__(self, spectrum: np.ndarray) -> float: ...

class HPCP(Algorithm):
    def __init__(self, bandPreset: bool = True, bandSplitFrequency: float = 500, harmonics: int = 0, maxFrequency: float = 5000, maxShifted: bool = False, minFrequency: float = 40, nonLinear: bool = False, normalized: str = 'unitMax', referenceFrequency: float = 440, sampleRate: float = 44100, size: int = 12, weightType: str = 'squaredCosine', windowSize: float = 1) -> None: ...
    def __call__(self, frequencies: np.ndarray, magnitudes: np.ndarray) -> np.ndarray: ...

class HarmonicBpm(Algorithm):
    def __init__(self, bpm: float = 60, threshold: float = 20, tolerance: float = 5) -> None: ...
    def __call__(self, bpms: np.ndarray) -> np.ndarray: ...

class HarmonicMask(Algorithm):
    def __init__(self, attenuation: float = -200, binWidth: int = 4, sampleRate: float = 44100) -> None: ...
    def __call__(self, fft: np.ndarray, pitch: float) -> np.ndarray: ...

class HarmonicModelAnal(Algorithm):
    def __init__(self, freqDevOffset: float = 20, freqDevSlope: float = 0.01, harmDevSlope: float = 0.01, hopSize: int = 512, magnitudeThreshold: float = -74, maxFrequency: float = 5000, maxPeaks: int = 100, maxnSines: int = 100, minFrequency: float = 20, nHarmonics: int = 100, orderBy: str = 'frequency', sampleRate: float = 44100) -> None: ...
    def __call__(self, fft: np.ndarray, pitch: float) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...

class HarmonicPeaks(Algorithm):
    def __init__(self, maxHarmonics: int = 20, tolerance: float = 0.2) -> None: ...
    def __call__(self, frequencies: np.ndarray, magnitudes: np.ndarray, pitch: float) -> tuple[np.ndarray, np.ndarray]: ...

class HighPass(Algorithm):
    def __init__(self, cutoffFrequency: float = 1500, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class HighResolutionFeatures(Algorithm):
    def __init__(self, maxPeaks: int = 24) -> None: ...
    def __call__(self, hpcp: np.ndarray) -> tuple[float, float, float]: ...

class Histogram(Algorithm):
    def __init__(self, maxValue: float = 1, minValue: float = 0, normalize: str = 'none', numberBins: int = 10) -> None: ...
    def __call__(self, array: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class HprModelAnal(Algorithm):
    def __init__(self, fftSize: int = 2048, freqDevOffset: int = 20, freqDevSlope: float = 0.01, harmDevSlope: float = 0.01, hopSize: int = 512, magnitudeThreshold: float = 0, maxFrequency: float = 5000, maxPeaks: int = 100, maxnSines: int = 100, minFrequency: float = 20, nHarmonics: int = 100, orderBy: str = 'frequency', sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def __call__(self, frame: np.ndarray, pitch: float) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...

class HpsModelAnal(Algorithm):
    def __init__(self, fftSize: int = 2048, freqDevOffset: int = 20, freqDevSlope: float = 0.01, harmDevSlope: float = 0.01, hopSize: int = 512, magnitudeThreshold: float = 0, maxFrequency: float = 5000, maxPeaks: int = 100, maxnSines: int = 100, minFrequency: float = 20, nHarmonics: int = 100, orderBy: str = 'frequency', sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def __call__(self, frame: np.ndarray, pitch: float) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...

class HumDetector(Algorithm):
    def __init__(self, Q0: float = 0.1, Q1: float = 0.55, detectionThreshold: float = 5, frameSize: float = 0.4, hopSize: float = 0.2, maximumFrequency: float = 400, minimumDuration: float = 2, minimumFrequency: float = 22.5, numberHarmonics: int = 1, sampleRate: float = 44100, timeContinuity: float = 10, timeWindow: float = 10) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...

class IDCT(Algorithm):
    def __init__(self, dctType: int = 2, inputSize: int = 10, liftering: int = 0, outputSize: int = 10) -> None: ...
    def __call__(self, dct: np.ndarray) -> np.ndarray: ...

class IFFT(Algorithm):
    def __init__(self, normalize: bool = True, size: int = 1024) -> None: ...
    def __call__(self, fft: np.ndarray) -> np.ndarray: ...

class IFFTC(Algorithm):
    def __init__(self, normalize: bool = True, size: int = 1024) -> None: ...
    def __call__(self, fft: np.ndarray) -> np.ndarray: ...

class IIR(Algorithm):
    def __init__(self, denominator: np.ndarray = '[1]', numerator: np.ndarray = '[1]') -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class Inharmonicity(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, frequencies: np.ndarray, magnitudes: np.ndarray) -> float: ...

class InstantPower(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class Intensity(Algorithm):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> int: ...

class Key(Algorithm):
    def __init__(self, numHarmonics: int = 4, pcpSize: int = 36, profileType: str = 'bgate', slope: float = 0.6, useMajMin: bool = False, usePolyphony: bool = True, useThreeChords: bool = True) -> None: ...
    def __call__(self, pcp: np.ndarray) -> tuple[str, str, float, float]: ...

class KeyExtractor(Algorithm):
    def __init__(self, averageDetuningCorrection: bool = True, frameSize: int = 4096, hopSize: int = 4096, hpcpSize: int = 12, maxFrequency: float = 3500, maximumSpectralPeaks: int = 60, minFrequency: float = 25, pcpThreshold: float = 0.2, profileType: str = 'bgate', sampleRate: float = 44100, spectralPeaksThreshold: float = 0.0001, tuningFrequency: float = 440, weightType: str = 'cosine', windowType: str = 'hann') -> None: ...
    def __call__(self, audio: np.ndarray) -> tuple[str, str, float]: ...

class LPC(Algorithm):
    def __init__(self, order: int = 10, sampleRate: float = 44100, type: str = 'regular') -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class Larm(Algorithm):
    def __init__(self, attackTime: float = 10, power: float = 1.5, releaseTime: float = 1500, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...

class Leq(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...

class LevelExtractor(Algorithm):
    def __init__(self, frameSize: int = 88200, hopSize: int = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class LogAttackTime(Algorithm):
    def __init__(self, sampleRate: float = 44100, startAttackThreshold: float = 0.2, stopAttackThreshold: float = 0.9) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[float, float, float]: ...

class LogSpectrum(Algorithm):
    def __init__(self, binsPerSemitone: float = 3, frameSize: int = 1025, nOctave: int = 7, rollOn: float = 0, sampleRate: float = 44100) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> tuple[np.ndarray, np.ndarray, float]: ...

class LoopBpmConfidence(Algorithm):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray, bpmEstimate: float) -> float: ...

class LoopBpmEstimator(Algorithm):
    def __init__(self, confidenceThreshold: float = 0.95) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...

class Loudness(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...

class LoudnessEBUR128(Algorithm):
    def __init__(self, hopSize: float = 0.1, sampleRate: float = 44100, startAtZero: bool = False) -> None: ...
    def __call__(self, signal: Any) -> tuple[np.ndarray, np.ndarray, float, float]: ...

class LoudnessVickers(Algorithm):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...

class LowLevelSpectralEqloudExtractor(Algorithm):
    def __init__(self, frameSize: int = 2048, hopSize: int = 1024, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[np.ndarray, Any, Any, np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...

class LowLevelSpectralExtractor(Algorithm):
    def __init__(self, frameSize: int = 2048, hopSize: int = 1024, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[Any, np.ndarray, np.ndarray, np.ndarray, np.ndarray, Any, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, Any, np.ndarray]: ...

class LowPass(Algorithm):
    def __init__(self, cutoffFrequency: float = 1500, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class MFCC(Algorithm):
    def __init__(self, dctType: int = 2, highFrequencyBound: float = 11000, inputSize: int = 1025, liftering: int = 0, logType: str = 'dbamp', lowFrequencyBound: float = 0, normalize: str = 'unit_sum', numberBands: int = 40, numberCoefficients: int = 13, sampleRate: float = 44100, silenceThreshold: float = 1e-10, type: str = 'power', warpingFormula: str = 'htkMel', weighting: str = 'warping') -> None: ...
    def __call__(self, spectrum: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class Magnitude(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, complex: np.ndarray) -> np.ndarray: ...

class MaxFilter(Algorithm):
    def __init__(self, causal: bool = True, width: int = 3) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class MaxMagFreq(Algorithm):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> float: ...

class MaxToTotal(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, envelope: np.ndarray) -> float: ...

class Mean(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class Median(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class MedianFilter(Algorithm):
    def __init__(self, kernelSize: int = 11) -> None: ...
    def __call__(self, array: np.ndarray) -> np.ndarray: ...

class MelBands(Algorithm):
    def __init__(self, highFrequencyBound: float = 22050, inputSize: int = 1025, log: bool = False, lowFrequencyBound: float = 0, normalize: str = 'unit_sum', numberBands: int = 24, sampleRate: float = 44100, type: str = 'power', warpingFormula: str = 'htkMel', weighting: str = 'warping') -> None: ...
    def __call__(self, spectrum: np.ndarray) -> np.ndarray: ...

class MetadataReader(Algorithm):
    def __init__(self, failOnError: bool = False, filename: str, filterMetadata: bool = False, filterMetadataTags: list[str] = '[]', tagPoolName: str = 'metadata.tags') -> None: ...
    def __call__(self) -> tuple[str, str, str, str, str, str, str, Pool, int, int, int, int]: ...

class Meter(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, beatogram: Any) -> float: ...

class MinMax(Algorithm):
    def __init__(self, type: str = 'min') -> None: ...
    def __call__(self, array: np.ndarray) -> tuple[float, int]: ...

class MinToTotal(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, envelope: np.ndarray) -> float: ...

class MonoLoader(Algorithm):
    def __init__(self, audioStream: int = 0, downmix: str = 'mix', filename: str, resampleQuality: int = 1, sampleRate: float = 44100) -> None: ...
    def __call__(self) -> np.ndarray: ...

class MonoMixer(Algorithm):
    def __init__(self, type: str = 'mix') -> None: ...
    def __call__(self, audio: Any, numberChannels: int) -> np.ndarray: ...

class MonoWriter(Algorithm):
    def __init__(self, bitrate: int = 192, filename: str, format: str = 'wav', sampleRate: float = 44100) -> None: ...
    def __call__(self, audio: np.ndarray) -> None: ...

class MovingAverage(Algorithm):
    def __init__(self, size: int = 6) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class MultiPitchKlapuri(Algorithm):
    def __init__(self, binResolution: float = 10, frameSize: int = 2048, harmonicWeight: float = 0.8, hopSize: int = 128, magnitudeCompression: float = 1, magnitudeThreshold: int = 40, maxFrequency: float = 1760, minFrequency: float = 80, numberHarmonics: int = 10, referenceFrequency: float = 55, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> Any: ...

class MultiPitchMelodia(Algorithm):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, frameSize: int = 2048, guessUnvoiced: bool = False, harmonicWeight: float = 0.8, hopSize: int = 128, magnitudeCompression: float = 1, magnitudeThreshold: int = 40, maxFrequency: float = 20000, minDuration: int = 100, minFrequency: float = 40, numberHarmonics: int = 20, peakDistributionThreshold: float = 0.9, peakFrameThreshold: float = 0.9, pitchContinuity: float = 27.5625, referenceFrequency: float = 55, sampleRate: float = 44100, timeContinuity: int = 100) -> None: ...
    def __call__(self, signal: np.ndarray) -> Any: ...

class Multiplexer(Algorithm):
    def __init__(self, numberRealInputs: int = 0, numberVectorRealInputs: int = 0) -> None: ...
    def __call__(self) -> Any: ...

class MusicExtractor(Algorithm):
    def __init__(self, analysisSampleRate: float = 44100, chromaprintCompute: bool = False, chromaprintDuration: float = 0, endTime: float = 1e+06, gfccStats: list[str] = '[“mean”', highlevel: list[str], loudnessFrameSize: int = 88200, loudnessHopSize: int = 44100, lowlevelFrameSize: int = 2048, lowlevelHopSize: int = 1024, lowlevelSilentFrames: str = 'noise', lowlevelStats: list[str] = '[“mean”', lowlevelWindowType: str = 'blackmanharris62', lowlevelZeroPadding: int = 0, mfccStats: list[str] = '[“mean”', profile: str, requireMbid: bool = False, rhythmMaxTempo: int = 208, rhythmMethod: str = 'degara', rhythmMinTempo: int = 40, rhythmStats: list[str] = '[“mean”', startTime: float = 0, tonalFrameSize: int = 4096, tonalHopSize: int = 2048, tonalSilentFrames: str = 'noise', tonalStats: list[str] = '[“mean”', tonalWindowType: str = 'blackmanharris62', tonalZeroPadding: int = 0) -> None: ...
    def __call__(self, filename: str) -> tuple[Pool, Pool]: ...

class NNLSChroma(Algorithm):
    def __init__(self, chromaNormalization: str = 'none', frameSize: int = 1025, sampleRate: float = 44100, spectralShape: float = 0.7, spectralWhitening: float = 1, tuningMode: str = 'global', useNNLS: bool = True) -> None: ...
    def __call__(self, logSpectrogram: Any, meanTuning: np.ndarray, localTuning: np.ndarray) -> tuple[Any, Any, Any, Any]: ...

class NSGConstantQ(Algorithm):
    def __init__(self, binsPerOctave: int = 48, gamma: int = 0, inputSize: int = 4096, maxFrequency: float = 7040, minFrequency: float = 27.5, minimumWindow: int = 4, normalize: str = 'none', phaseMode: str = 'global', rasterize: str = 'full', sampleRate: float = 44100, window: str = 'hannnsgcq', windowSizeFactor: int = 1) -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[Any, np.ndarray, np.ndarray]: ...

class NSGIConstantQ(Algorithm):
    def __init__(self, binsPerOctave: int = 48, gamma: int = 0, inputSize: int = 4096, maxFrequency: float = 7040, minFrequency: float = 27.5, minimumWindow: int = 4, normalize: str = 'none', phaseMode: str = 'global', rasterize: str = 'full', sampleRate: float = 44100, window: str = 'hannnsgcq', windowSizeFactor: int = 1) -> None: ...
    def __call__(self, constantq: Any, constantqdc: np.ndarray, constantqnf: np.ndarray) -> np.ndarray: ...

class NoiseAdder(Algorithm):
    def __init__(self, fixSeed: bool = False, level: int = -100) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class NoiseBurstDetector(Algorithm):
    def __init__(self, alpha: float = 0.9, silenceThreshold: int = -50, threshold: int = 8) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class NoveltyCurve(Algorithm):
    def __init__(self, frameRate: float = 344.531, normalize: bool = False, weightCurve: np.ndarray = '[]', weightCurveType: str = 'hybrid') -> None: ...
    def __call__(self, frequencyBands: Any) -> np.ndarray: ...

class NoveltyCurveFixedBpmEstimator(Algorithm):
    def __init__(self, hopSize: int = 512, maxBpm: float = 560, minBpm: float = 30, sampleRate: float = 44100, tolerance: float = 3) -> None: ...
    def __call__(self, novelty: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class OddToEvenHarmonicEnergyRatio(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, frequencies: np.ndarray, magnitudes: np.ndarray) -> float: ...

class OnsetDetection(Algorithm):
    def __init__(self, method: str = 'hfc', sampleRate: float = 44100) -> None: ...
    def __call__(self, spectrum: np.ndarray, phase: np.ndarray) -> float: ...

class OnsetDetectionGlobal(Algorithm):
    def __init__(self, frameSize: int = 2048, hopSize: int = 512, method: str = 'infogain', sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class OnsetRate(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[np.ndarray, float]: ...

class Onsets(Algorithm):
    def __init__(self, alpha: float = 0.1, delay: int = 5, frameRate: float = 86.1328, silenceThreshold: float = 0.02) -> None: ...
    def __call__(self, detections: np.ndarray, weights: np.ndarray) -> np.ndarray: ...

class OverlapAdd(Algorithm):
    def __init__(self, frameSize: int = 2048, gain: float = 1, hopSize: int = 128) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class PCA(Algorithm):
    def __init__(self, dimensions: int = 0, namespaceIn: str = 'spectral', namespaceOut: str = 'spectral') -> None: ...
    def __call__(self, poolIn: Pool) -> Pool: ...

class Panning(Algorithm):
    def __init__(self, averageFrames: int = 43, numBands: int = 1, numCoeffs: int = 20, panningBins: int = 512, sampleRate: float = 44100, warpedPanorama: bool = True) -> None: ...
    def __call__(self, spectrumLeft: np.ndarray, spectrumRight: np.ndarray) -> np.ndarray: ...

class PeakDetection(Algorithm):
    def __init__(self, interpolate: bool = True, maxPeaks: int = 100, maxPosition: float = 1, minPeakDistance: float = 0, minPosition: float = 0, orderBy: str = 'position', range: float = 1, threshold: float = -1e+06) -> None: ...
    def __call__(self, array: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class PercivalBpmEstimator(Algorithm):
    def __init__(self, frameSize: int = 1024, frameSizeOSS: int = 2048, hopSize: int = 128, hopSizeOSS: int = 128, maxBPM: int = 210, minBPM: int = 50, sampleRate: int = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...

class PercivalEnhanceHarmonics(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> np.ndarray: ...

class PercivalEvaluatePulseTrains(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, oss: np.ndarray, positions: np.ndarray) -> float: ...

class Pitch2Midi(Algorithm):
    def __init__(self, applyTimeCompensation: bool = True, hopSize: int = 128, midiBufferDuration: float = 0.015, minFrequency: float = 60, minNoteChangePeriod: float = 0.03, minOccurrenceRate: float = 0.5, minOffsetCheckPeriod: float = 0.2, minOnsetCheckPeriod: float = 0.075, sampleRate: int = 44100, transpositionAmount: int = 0, tuningFrequency: int = 440) -> None: ...
    def __call__(self, pitch: float, voiced: int) -> tuple[list[str], np.ndarray, np.ndarray]: ...

class PitchContourSegmentation(Algorithm):
    def __init__(self, hopSize: int = 128, minDuration: float = 0.1, pitchDistanceThreshold: int = 60, rmsThreshold: int = -2, sampleRate: int = 44100, tuningFrequency: int = 440) -> None: ...
    def __call__(self, pitch: np.ndarray, signal: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...

class PitchContours(Algorithm):
    def __init__(self, binResolution: float = 10, hopSize: int = 128, minDuration: float = 100, peakDistributionThreshold: float = 0.9, peakFrameThreshold: float = 0.9, pitchContinuity: float = 27.5625, sampleRate: float = 44100, timeContinuity: float = 100) -> None: ...
    def __call__(self, peakBins: Any, peakSaliences: Any) -> tuple[Any, Any, np.ndarray, float]: ...

class PitchContoursMelody(Algorithm):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, guessUnvoiced: bool = False, hopSize: int = 128, maxFrequency: float = 20000, minFrequency: float = 80, referenceFrequency: float = 55, sampleRate: float = 44100, voiceVibrato: bool = False, voicingTolerance: float = 0.2) -> None: ...
    def __call__(self, contoursBins: Any, contoursSaliences: Any, contoursStartTimes: np.ndarray, duration: float) -> tuple[np.ndarray, np.ndarray]: ...

class PitchContoursMonoMelody(Algorithm):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, guessUnvoiced: bool = False, hopSize: int = 128, maxFrequency: float = 20000, minFrequency: float = 80, referenceFrequency: float = 55, sampleRate: float = 44100) -> None: ...
    def __call__(self, contoursBins: Any, contoursSaliences: Any, contoursStartTimes: np.ndarray, duration: float) -> tuple[np.ndarray, np.ndarray]: ...

class PitchContoursMultiMelody(Algorithm):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, guessUnvoiced: bool = False, hopSize: int = 128, maxFrequency: float = 20000, minFrequency: float = 80, referenceFrequency: float = 55, sampleRate: float = 44100) -> None: ...
    def __call__(self, contoursBins: Any, contoursSaliences: Any, contoursStartTimes: np.ndarray, duration: float) -> Any: ...

class PitchFilter(Algorithm):
    def __init__(self, confidenceThreshold: int = 36, minChunkSize: int = 30, useAbsolutePitchConfidence: bool = False) -> None: ...
    def __call__(self, pitch: np.ndarray, pitchConfidence: np.ndarray) -> np.ndarray: ...

class PitchMelodia(Algorithm):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, frameSize: int = 2048, guessUnvoiced: bool = False, harmonicWeight: float = 0.8, hopSize: int = 128, magnitudeCompression: float = 1, magnitudeThreshold: int = 40, maxFrequency: float = 20000, minDuration: int = 100, minFrequency: float = 40, numberHarmonics: int = 20, peakDistributionThreshold: float = 0.9, peakFrameThreshold: float = 0.9, pitchContinuity: float = 27.5625, referenceFrequency: float = 55, sampleRate: float = 44100, timeContinuity: int = 100) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class PitchSalience(Algorithm):
    def __init__(self, highBoundary: float = 5000, lowBoundary: float = 100, sampleRate: float = 44100) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> float: ...

class PitchSalienceFunction(Algorithm):
    def __init__(self, binResolution: float = 10, harmonicWeight: float = 0.8, magnitudeCompression: float = 1, magnitudeThreshold: float = 40, numberHarmonics: int = 20, referenceFrequency: float = 55) -> None: ...
    def __call__(self, frequencies: np.ndarray, magnitudes: np.ndarray) -> np.ndarray: ...

class PitchSalienceFunctionPeaks(Algorithm):
    def __init__(self, binResolution: float = 10, maxFrequency: float = 1760, minFrequency: float = 55, referenceFrequency: float = 55) -> None: ...
    def __call__(self, salienceFunction: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class PitchYin(Algorithm):
    def __init__(self, frameSize: int = 2048, interpolate: bool = True, maxFrequency: float = 22050, minFrequency: float = 20, sampleRate: float = 44100, tolerance: float = 0.15) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[float, float]: ...

class PitchYinFFT(Algorithm):
    def __init__(self, frameSize: int = 2048, interpolate: bool = True, maxFrequency: float = 22050, minFrequency: float = 20, sampleRate: float = 44100, tolerance: float = 1, weighting: str = 'custom') -> None: ...
    def __call__(self, spectrum: np.ndarray) -> tuple[float, float]: ...

class PitchYinProbabilistic(Algorithm):
    def __init__(self, frameSize: int = 2048, hopSize: int = 256, lowRMSThreshold: float = 0.1, outputUnvoiced: str = 'negative', preciseTime: bool = False, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class PitchYinProbabilities(Algorithm):
    def __init__(self, frameSize: int = 2048, lowAmp: float = 0.1, preciseTime: bool = False, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[np.ndarray, np.ndarray, float]: ...

class PitchYinProbabilitiesHMM(Algorithm):
    def __init__(self, minFrequency: float = 61.735, numberBinsPerSemitone: int = 5, selfTransition: float = 0.99, yinTrust: float = 0.5) -> None: ...
    def __call__(self, pitchCandidates: Any, probabilities: Any) -> np.ndarray: ...

class PolarToCartesian(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, magnitude: np.ndarray, phase: np.ndarray) -> np.ndarray: ...

class PoolAggregator(Algorithm):
    def __init__(self, defaultStats: list[str] = '[“mean”', exceptions: Any = '{}') -> None: ...
    def __call__(self, input: Pool) -> Pool: ...

class PowerMean(Algorithm):
    def __init__(self, power: float = 1) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class PowerSpectrum(Algorithm):
    def __init__(self, size: int = 2048) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class PredominantPitchMelodia(Algorithm):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, frameSize: int = 2048, guessUnvoiced: bool = False, harmonicWeight: float = 0.8, hopSize: int = 128, magnitudeCompression: float = 1, magnitudeThreshold: int = 40, maxFrequency: float = 20000, minDuration: int = 100, minFrequency: float = 80, numberHarmonics: int = 20, peakDistributionThreshold: float = 0.9, peakFrameThreshold: float = 0.9, pitchContinuity: float = 27.5625, referenceFrequency: float = 55, sampleRate: float = 44100, timeContinuity: int = 100, voiceVibrato: bool = False, voicingTolerance: float = 0.2) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class RMS(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class RawMoments(Algorithm):
    def __init__(self, range: float = 22050) -> None: ...
    def __call__(self, array: np.ndarray) -> np.ndarray: ...

class ReplayGain(Algorithm):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...

class Resample(Algorithm):
    def __init__(self, inputSampleRate: float = 44100, outputSampleRate: float = 44100, quality: int = 1) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class ResampleFFT(Algorithm):
    def __init__(self, inSize: int = 128, outSize: int = 128) -> None: ...
    def __call__(self, input: np.ndarray) -> np.ndarray: ...

class RhythmDescriptors(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[np.ndarray, float, float, np.ndarray, np.ndarray, float, float, float, float, float, float, np.ndarray]: ...

class RhythmExtractor(Algorithm):
    def __init__(self, frameHop: int = 1024, frameSize: int = 1024, hopSize: int = 256, lastBeatInterval: float = 0.1, maxTempo: int = 208, minTempo: int = 40, numberFrames: int = 1024, sampleRate: float = 44100, tempoHints: np.ndarray = '[]', tolerance: float = 0.24, useBands: bool = True, useOnset: bool = True) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[float, np.ndarray, np.ndarray, np.ndarray]: ...

class RhythmExtractor2013(Algorithm):
    def __init__(self, maxTempo: int = 208, method: str = 'multifeature', minTempo: int = 40) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[float, np.ndarray, float, np.ndarray, np.ndarray]: ...

class RhythmTransform(Algorithm):
    def __init__(self, frameSize: int = 256, hopSize: int = 32) -> None: ...
    def __call__(self, melBands: Any) -> Any: ...

class RollOff(Algorithm):
    def __init__(self, cutoff: float = 0.85, sampleRate: float = 44100) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> float: ...

class SBic(Algorithm):
    def __init__(self, cpw: float = 1.5, inc1: int = 60, inc2: int = 20, minLength: int = 10, size1: int = 300, size2: int = 200) -> None: ...
    def __call__(self, features: np.ndarray) -> np.ndarray: ...

class SNR(Algorithm):
    def __init__(self, MAAlpha: float = 0.95, MMSEAlpha: float = 0.98, NoiseAlpha: float = 0.9, frameSize: int = 512, noiseThreshold: float = -40, sampleRate: float = 44100, useBroadbadNoiseCorrection: bool = True) -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[float, float, np.ndarray]: ...

class SaturationDetector(Algorithm):
    def __init__(self, differentialThreshold: float = 0.001, energyThreshold: float = -1, frameSize: int = 512, hopSize: int = 256, minimumDuration: float = 0.005, sampleRate: float = 44100) -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class Scale(Algorithm):
    def __init__(self, clipping: bool = True, factor: float = 10, maxAbsValue: float = 1) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class SilenceRate(Algorithm):
    def __init__(self, thresholds: np.ndarray = '[]') -> None: ...
    def __call__(self, frame: np.ndarray) -> None: ...

class SineModelAnal(Algorithm):
    def __init__(self, freqDevOffset: float = 20, freqDevSlope: float = 0.01, magnitudeThreshold: float = -74, maxFrequency: float = 22050, maxPeaks: int = 250, maxnSines: int = 100, minFrequency: float = 0, orderBy: str = 'frequency', sampleRate: float = 44100) -> None: ...
    def __call__(self, fft: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...

class SineModelSynth(Algorithm):
    def __init__(self, fftSize: int = 2048, hopSize: int = 512, sampleRate: float = 44100) -> None: ...
    def __call__(self, magnitudes: np.ndarray, frequencies: np.ndarray, phases: np.ndarray) -> np.ndarray: ...

class SineSubtraction(Algorithm):
    def __init__(self, fftSize: int = 512, hopSize: int = 128, sampleRate: float = 44100) -> None: ...
    def __call__(self, frame: np.ndarray, magnitudes: np.ndarray, frequencies: np.ndarray, phases: np.ndarray) -> np.ndarray: ...

class SingleBeatLoudness(Algorithm):
    def __init__(self, beatDuration: float = 0.05, beatWindowDuration: float = 0.1, frequencyBands: np.ndarray = '[0', onsetStart: str = 'sumEnergy', sampleRate: float = 44100) -> None: ...
    def __call__(self, beat: np.ndarray) -> tuple[float, np.ndarray]: ...

class SingleGaussian(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...

class Slicer(Algorithm):
    def __init__(self, endTimes: np.ndarray = '[]', sampleRate: float = 44100, startTimes: np.ndarray = '[]', timeUnits: str = 'seconds') -> None: ...
    def __call__(self, audio: np.ndarray) -> Any: ...

class SpectralCentroidTime(Algorithm):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class SpectralComplexity(Algorithm):
    def __init__(self, magnitudeThreshold: float = 0.005, sampleRate: float = 44100) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> float: ...

class SpectralContrast(Algorithm):
    def __init__(self, frameSize: int = 2048, highFrequencyBound: float = 11000, lowFrequencyBound: float = 20, neighbourRatio: float = 0.4, numberBands: int = 6, sampleRate: float = 22050, staticDistribution: float = 0.15) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class SpectralPeaks(Algorithm):
    def __init__(self, magnitudeThreshold: float = 0, maxFrequency: float = 5000, maxPeaks: int = 100, minFrequency: float = 0, orderBy: str = 'frequency', sampleRate: float = 44100) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class SpectralWhitening(Algorithm):
    def __init__(self, maxFrequency: float = 5000, sampleRate: float = 44100) -> None: ...
    def __call__(self, spectrum: np.ndarray, frequencies: np.ndarray, magnitudes: np.ndarray) -> np.ndarray: ...

class Spectrum(Algorithm):
    def __init__(self, size: int = 2048) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class SpectrumCQ(Algorithm):
    def __init__(self, binsPerOctave: int = 12, minFrequency: float = 32.7, minimumKernelSize: int = 4, numberBins: int = 84, sampleRate: float = 44100, scale: float = 1, threshold: float = 0.01, windowType: str = 'hann', zeroPhase: bool = True) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class SpectrumToCent(Algorithm):
    def __init__(self, bands: int = 720, centBinResolution: float = 10, inputSize: int = 32768, log: bool = True, minimumFrequency: float = 164, normalize: str = 'unit_sum', sampleRate: float = 44100, type: str = 'power') -> None: ...
    def __call__(self, spectrum: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class Spline(Algorithm):
    def __init__(self, beta1: float = 1, beta2: float = 0, type: str = 'b', xPoints: np.ndarray = '[0', yPoints: np.ndarray = '[0') -> None: ...
    def __call__(self, x: float) -> float: ...

class SprModelAnal(Algorithm):
    def __init__(self, fftSize: int = 2048, freqDevOffset: int = 20, freqDevSlope: float = 0.01, hopSize: int = 512, magnitudeThreshold: float = 0, maxFrequency: float = 5000, maxPeaks: int = 100, maxnSines: int = 100, minFrequency: float = 0, orderBy: str = 'frequency', sampleRate: float = 44100) -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...

class SprModelSynth(Algorithm):
    def __init__(self, fftSize: int = 2048, hopSize: int = 512, sampleRate: float = 44100) -> None: ...
    def __call__(self, magnitudes: np.ndarray, frequencies: np.ndarray, phases: np.ndarray, res: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...

class SpsModelAnal(Algorithm):
    def __init__(self, fftSize: int = 2048, freqDevOffset: int = 20, freqDevSlope: float = 0.01, hopSize: int = 512, magnitudeThreshold: float = 0, maxFrequency: float = 5000, maxPeaks: int = 100, maxnSines: int = 100, minFrequency: float = 0, orderBy: str = 'frequency', sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...

class SpsModelSynth(Algorithm):
    def __init__(self, fftSize: int = 2048, hopSize: int = 512, sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def __call__(self, magnitudes: np.ndarray, frequencies: np.ndarray, phases: np.ndarray, stocenv: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...

class StartStopCut(Algorithm):
    def __init__(self, frameSize: int = 256, hopSize: int = 256, maximumStartTime: float = 10, maximumStopTime: float = 10, sampleRate: float = 44100, threshold: int = -60) -> None: ...
    def __call__(self, audio: np.ndarray) -> tuple[int, int]: ...

class StartStopSilence(Algorithm):
    def __init__(self, threshold: int = -60) -> None: ...
    def __call__(self, frame: np.ndarray) -> tuple[int, int]: ...

class StereoDemuxer(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, audio: Any) -> tuple[np.ndarray, np.ndarray]: ...

class StereoMuxer(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, left: np.ndarray, right: np.ndarray) -> Any: ...

class StereoTrimmer(Algorithm):
    def __init__(self, checkRange: bool = False, endTime: float = 1e+06, sampleRate: float = 44100, startTime: float = 0) -> None: ...
    def __call__(self, signal: Any) -> Any: ...

class StochasticModelAnal(Algorithm):
    def __init__(self, fftSize: int = 2048, hopSize: int = 512, sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class StochasticModelSynth(Algorithm):
    def __init__(self, fftSize: int = 2048, hopSize: int = 512, sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def __call__(self, stocenv: np.ndarray) -> np.ndarray: ...

class StrongDecay(Algorithm):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...

class StrongPeak(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, spectrum: np.ndarray) -> float: ...

class SuperFluxExtractor(Algorithm):
    def __init__(self, combine: float = 20, frameSize: int = 2048, hopSize: int = 256, ratioThreshold: float = 16, sampleRate: float = 44100, threshold: float = 0.05) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class SuperFluxNovelty(Algorithm):
    def __init__(self, binWidth: int = 3, frameWidth: int = 2) -> None: ...
    def __call__(self, bands: Any) -> float: ...

class SuperFluxPeaks(Algorithm):
    def __init__(self, combine: float = 30, frameRate: float = 172, pre_avg: float = 100, pre_max: float = 30, ratioThreshold: float = 16, threshold: float = 0.05) -> None: ...
    def __call__(self, novelty: np.ndarray) -> np.ndarray: ...

class TCToTotal(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, envelope: np.ndarray) -> float: ...

class TempoScaleBands(Algorithm):
    def __init__(self, bandsGain: np.ndarray = '[2', frameTime: float = 512) -> None: ...
    def __call__(self, bands: np.ndarray) -> tuple[np.ndarray, float]: ...

class TempoTap(Algorithm):
    def __init__(self, frameHop: int = 1024, frameSize: int = 256, maxTempo: int = 208, minTempo: int = 40, numberFrames: int = 1024, sampleRate: float = 44100, tempoHints: np.ndarray = '[]') -> None: ...
    def __call__(self, featuresFrame: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class TempoTapDegara(Algorithm):
    def __init__(self, maxTempo: int = 208, minTempo: int = 40, resample: str = 'none', sampleRateODF: float = 86.1328) -> None: ...
    def __call__(self, onsetDetections: np.ndarray) -> np.ndarray: ...

class TempoTapMaxAgreement(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, tickCandidates: Any) -> tuple[np.ndarray, float]: ...

class TempoTapTicks(Algorithm):
    def __init__(self, frameHop: int = 512, hopSize: int = 256, sampleRate: float = 44100) -> None: ...
    def __call__(self, periods: np.ndarray, phases: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class TensorNormalize(Algorithm):
    def __init__(self, axis: int = 0, scaler: str = 'standard', skipConstantSlices: bool = True) -> None: ...
    def __call__(self, tensor: np.ndarray) -> np.ndarray: ...

class TensorTranspose(Algorithm):
    def __init__(self, permutation: Any) -> None: ...
    def __call__(self, tensor: np.ndarray) -> np.ndarray: ...

class TensorflowInputFSDSINet(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class TensorflowInputMusiCNN(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class TensorflowInputTempoCNN(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class TensorflowInputVGGish(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class TonalExtractor(Algorithm):
    def __init__(self, frameSize: int = 4096, hopSize: int = 2048, tuningFrequency: float = 440) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[float, np.ndarray, str, float, list[str], str, np.ndarray, Any, Any, str, str, float]: ...

class TonicIndianArtMusic(Algorithm):
    def __init__(self, binResolution: float = 10, frameSize: int = 2048, harmonicWeight: float = 0.85, hopSize: int = 512, magnitudeCompression: float = 1, magnitudeThreshold: float = 40, maxTonicFrequency: float = 375, minTonicFrequency: float = 100, numberHarmonics: int = 20, numberSaliencePeaks: int = 5, referenceFrequency: float = 55, sampleRate: float = 44100) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...

class TriangularBands(Algorithm):
    def __init__(self, frequencyBands: np.ndarray = '[21.533203125', inputSize: int = 1025, log: bool = True, normalize: str = 'unit_sum', sampleRate: float = 44100, type: str = 'power', weighting: str = 'linear') -> None: ...
    def __call__(self, spectrum: np.ndarray) -> np.ndarray: ...

class TriangularBarkBands(Algorithm):
    def __init__(self, highFrequencyBound: float = 22050, inputSize: int = 1025, log: bool = False, lowFrequencyBound: float = 0, normalize: str = 'unit_sum', numberBands: int = 24, sampleRate: float = 44100, type: str = 'power', weighting: str = 'warping') -> None: ...
    def __call__(self, spectrum: np.ndarray) -> np.ndarray: ...

class Trimmer(Algorithm):
    def __init__(self, checkRange: bool = False, endTime: float = 1e+06, sampleRate: float = 44100, startTime: float = 0) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class Tristimulus(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, frequencies: np.ndarray, magnitudes: np.ndarray) -> np.ndarray: ...

class TruePeakDetector(Algorithm):
    def __init__(self, blockDC: bool = False, emphasise: bool = False, oversamplingFactor: int = 4, quality: int = 1, sampleRate: float = 44100, threshold: float = -0.0002, version: int = 4) -> None: ...
    def __call__(self, signal: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class TuningFrequency(Algorithm):
    def __init__(self, resolution: float = 1) -> None: ...
    def __call__(self, frequencies: np.ndarray, magnitudes: np.ndarray) -> tuple[float, float]: ...

class TuningFrequencyExtractor(Algorithm):
    def __init__(self, frameSize: int = 4096, hopSize: int = 2048) -> None: ...
    def __call__(self, signal: np.ndarray) -> np.ndarray: ...

class UnaryOperator(Algorithm):
    def __init__(self, scale: float = 1, shift: float = 0, type: str = 'identity') -> None: ...
    def __call__(self, array: np.ndarray) -> np.ndarray: ...

class UnaryOperatorStream(Algorithm):
    def __init__(self, scale: float = 1, shift: float = 0, type: str = 'identity') -> None: ...
    def __call__(self, array: np.ndarray) -> np.ndarray: ...

class Variance(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, array: np.ndarray) -> float: ...

class Vibrato(Algorithm):
    def __init__(self, maxExtend: float = 250, maxFrequency: float = 8, minExtend: float = 50, minFrequency: float = 4, sampleRate: float = 344.531) -> None: ...
    def __call__(self, pitch: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...

class Viterbi(Algorithm):
    def __init__(self) -> None: ...
    def __call__(self, observationProbabilities: Any, initialization: np.ndarray, fromIndex: Any, toIndex: Any, transitionProbabilities: np.ndarray) -> Any: ...

class WarpedAutoCorrelation(Algorithm):
    def __init__(self, maxLag: int = 1, sampleRate: float = 44100) -> None: ...
    def __call__(self, array: np.ndarray) -> np.ndarray: ...

class Welch(Algorithm):
    def __init__(self, averagingFrames: int = 10, fftSize: int = 1024, frameSize: int = 512, sampleRate: float = 44100, scaling: str = 'density', windowType: str = 'hann') -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class Windowing(Algorithm):
    def __init__(self, constantsDecimals: int = 5, normalized: bool = True, size: int = 1024, splitPadding: bool = False, symmetric: bool = True, type: str = 'hann', zeroPadding: int = 0, zeroPhase: bool = True) -> None: ...
    def __call__(self, frame: np.ndarray) -> np.ndarray: ...

class YamlInput(Algorithm):
    def __init__(self, filename: str, format: str = 'yaml') -> None: ...
    def __call__(self) -> Pool: ...

class YamlOutput(Algorithm):
    def __init__(self, doubleCheck: bool = False, filename: str = '-', format: str = 'yaml', indent: int = 4, writeVersion: bool = True) -> None: ...
    def __call__(self, pool: Pool) -> None: ...

class ZeroCrossingRate(Algorithm):
    def __init__(self, threshold: float = 0) -> None: ...
    def __call__(self, signal: np.ndarray) -> float: ...
