"""
Type stubs for essentia.streaming algorithms.

Auto-generated -- 245 algorithms.
"""

from typing import Any, Tuple
import numpy.typing as npt
import numpy as np
from essentia._essentia import StreamingAlgorithm as Algo
from essentia import Pool

class AfterMaxToBeforeMaxEnergyRatio(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class AllPass(Algo):
    def __init__(self, bandwidth: float = 500, cutoffFrequency: float = 1500, order: int = 1, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class AudioLoader(Algo):
    def __init__(self, audioStream: int = 0, computeMD5: bool = False, filename: str) -> None: ...
    def configure(self, **kwargs) -> None: ...

class AudioOnsetsMarker(Algo):
    def __init__(self, onsets: np.ndarray = '[]', sampleRate: float = 44100, type: str = 'beep') -> None: ...
    def configure(self, **kwargs) -> None: ...

class AudioWriter(Algo):
    def __init__(self, bitrate: int = 192, filename: str, format: str = 'wav', sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class AutoCorrelation(Algo):
    def __init__(self, frequencyDomainCompression: float = 0.5, generalized: bool = False, normalization: str = 'standard') -> None: ...
    def configure(self, **kwargs) -> None: ...

class BFCC(Algo):
    def __init__(self, dctType: int = 2, highFrequencyBound: float = 11000, inputSize: int = 1025, liftering: int = 0, logType: str = 'dbamp', lowFrequencyBound: float = 0, normalize: str = 'unit_sum', numberBands: int = 40, numberCoefficients: int = 13, sampleRate: float = 44100, type: str = 'power', weighting: str = 'warping') -> None: ...
    def configure(self, **kwargs) -> None: ...

class BPF(Algo):
    def __init__(self, xPoints: np.ndarray = '[0', yPoints: np.ndarray = '[0') -> None: ...
    def configure(self, **kwargs) -> None: ...

class BandPass(Algo):
    def __init__(self, bandwidth: float = 500, cutoffFrequency: float = 1500, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class BandReject(Algo):
    def __init__(self, bandwidth: float = 500, cutoffFrequency: float = 1500, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class BarkBands(Algo):
    def __init__(self, numberBands: int = 27, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class BarkExtractor(Algo):
    def __init__(self, frameSize: int = 2048, hopSize: int = 1024, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class BeatTrackerDegara(Algo):
    def __init__(self, maxTempo: int = 208, minTempo: int = 40) -> None: ...
    def configure(self, **kwargs) -> None: ...

class BeatTrackerMultiFeature(Algo):
    def __init__(self, maxTempo: int = 208, minTempo: int = 40) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Beatogram(Algo):
    def __init__(self, size: int = 16) -> None: ...
    def configure(self, **kwargs) -> None: ...

class BeatsLoudness(Algo):
    def __init__(self, beatDuration: float = 0.05, beatWindowDuration: float = 0.1, beats: np.ndarray = '[]', frequencyBands: np.ndarray = '[0', sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class BinaryOperator(Algo):
    def __init__(self, type: str = 'add') -> None: ...
    def configure(self, **kwargs) -> None: ...

class BinaryOperatorStream(Algo):
    def __init__(self, type: str = 'add') -> None: ...
    def configure(self, **kwargs) -> None: ...

class BpmHistogram(Algo):
    def __init__(self, bpm: float = 0, constantTempo: bool = False, frameRate: float = 86.1328, frameSize: float = 4, maxBpm: float = 560, maxPeaks: int = 50, minBpm: float = 30, overlap: int = 16, tempoChange: float = 5, weightByMagnitude: bool = True, windowType: str = 'hann', zeroPadding: int = 0) -> None: ...
    def configure(self, **kwargs) -> None: ...

class BpmHistogramDescriptors(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class BpmRubato(Algo):
    def __init__(self, longRegionsPruningTime: float = 20, shortRegionsMergingTime: float = 4, tolerance: float = 0.08) -> None: ...
    def configure(self, **kwargs) -> None: ...

class CartesianToPolar(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class CentralMoments(Algo):
    def __init__(self, mode: str = 'pdf', range: float = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Centroid(Algo):
    def __init__(self, range: float = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class ChordsDescriptors(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class ChordsDetection(Algo):
    def __init__(self, hopSize: int = 2048, sampleRate: float = 44100, windowSize: float = 2) -> None: ...
    def configure(self, **kwargs) -> None: ...

class ChromaCrossSimilarity(Algo):
    def __init__(self, binarizePercentile: float = 0.095, frameStackSize: int = 9, frameStackStride: int = 1, oti: int = 0, otiBinary: bool = False, referenceFeature: Any = '[]') -> None: ...
    def configure(self, **kwargs) -> None: ...

class Chromagram(Algo):
    def __init__(self, binsPerOctave: int = 12, minFrequency: float = 32.7, minimumKernelSize: int = 4, normalizeType: str = 'unit_max', numberBins: int = 84, sampleRate: float = 44100, scale: float = 1, threshold: float = 0.01, windowType: str = 'hann', zeroPhase: bool = True) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Chromaprinter(Algo):
    def __init__(self, analysisTime: float = 30, concatenate: bool = True, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class ClickDetector(Algo):
    def __init__(self, detectionThreshold: float = 30, frameSize: int = 512, hopSize: int = 256, order: int = 12, powerEstimationThreshold: int = 10, sampleRate: float = 44100, silenceThreshold: int = -50) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Clipper(Algo):
    def __init__(self, max: float = 1, min: float = -1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class ConstantQ(Algo):
    def __init__(self, binsPerOctave: int = 12, minFrequency: float = 32.7, minimumKernelSize: int = 4, numberBins: int = 84, sampleRate: float = 44100, scale: float = 1, threshold: float = 0.01, windowType: str = 'hann', zeroPhase: bool = True) -> None: ...
    def configure(self, **kwargs) -> None: ...

class CoverSongSimilarity(Algo):
    def __init__(self, disExtension: float = 0.5, disOnset: float = 0.5, distanceType: str = 'asymmetric', pipeDistance: bool = False) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Crest(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class CrossCorrelation(Algo):
    def __init__(self, maxLag: int = 1, minLag: int = 0) -> None: ...
    def configure(self, **kwargs) -> None: ...

class CubicSpline(Algo):
    def __init__(self, leftBoundaryFlag: int = 0, leftBoundaryValue: float = 0, rightBoundaryFlag: int = 0, rightBoundaryValue: float = 0, xPoints: np.ndarray = '[0', yPoints: np.ndarray = '[0') -> None: ...
    def configure(self, **kwargs) -> None: ...

class DCRemoval(Algo):
    def __init__(self, cutoffFrequency: float = 40, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class DCT(Algo):
    def __init__(self, dctType: int = 2, inputSize: int = 10, liftering: int = 0, outputSize: int = 10) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Danceability(Algo):
    def __init__(self, maxTau: float = 8800, minTau: float = 310, sampleRate: float = 44100, tauMultiplier: float = 1.1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Decrease(Algo):
    def __init__(self, range: float = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Derivative(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class DerivativeSFX(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class DiscontinuityDetector(Algo):
    def __init__(self, detectionThreshold: float = 8, energyThreshold: float = -60, frameSize: int = 512, hopSize: int = 256, kernelSize: int = 7, order: int = 3, silenceThreshold: int = -50, subFrameSize: int = 32) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Dissonance(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class DistributionShape(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Duration(Algo):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class DynamicComplexity(Algo):
    def __init__(self, frameSize: float = 0.2, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class ERBBands(Algo):
    def __init__(self, highFrequencyBound: float = 22050, inputSize: int = 1025, lowFrequencyBound: float = 50, numberBands: int = 40, sampleRate: float = 44100, type: str = 'power', width: float = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class EasyLoader(Algo):
    def __init__(self, audioStream: int = 0, downmix: str = 'mix', endTime: float = 1e+06, filename: str, replayGain: float = -6, sampleRate: float = 44100, startTime: float = 0) -> None: ...
    def configure(self, **kwargs) -> None: ...

class EffectiveDuration(Algo):
    def __init__(self, sampleRate: float = 44100, thresholdRatio: float = 0.4) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Energy(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class EnergyBand(Algo):
    def __init__(self, sampleRate: float = 44100, startCutoffFrequency: float = 0, stopCutoffFrequency: float = 100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class EnergyBandRatio(Algo):
    def __init__(self, sampleRate: float = 44100, startFrequency: float = 0, stopFrequency: float = 100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Entropy(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Envelope(Algo):
    def __init__(self, applyRectification: bool = True, attackTime: float = 10, releaseTime: float = 1500, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class EqloudLoader(Algo):
    def __init__(self, downmix: str = 'mix', endTime: float = 1e+06, filename: str, replayGain: float = -6, sampleRate: float = 44100, startTime: float = 0) -> None: ...
    def configure(self, **kwargs) -> None: ...

class EqualLoudness(Algo):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class FFT(Algo):
    def __init__(self, size: int = 1024) -> None: ...
    def configure(self, **kwargs) -> None: ...

class FFTC(Algo):
    def __init__(self, negativeFrequencies: bool = False, size: int = 1024) -> None: ...
    def configure(self, **kwargs) -> None: ...

class FadeDetection(Algo):
    def __init__(self, cutoffHigh: float = 0.85, cutoffLow: float = 0.2, frameRate: float = 4, minLength: float = 3) -> None: ...
    def configure(self, **kwargs) -> None: ...

class FalseStereoDetector(Algo):
    def __init__(self, correlationThreshold: float = 0.9995, frameSize: int = 512, silenceThreshold: int = -70) -> None: ...
    def configure(self, **kwargs) -> None: ...

class FileOutput(Algo):
    def __init__(self, filename: str = 'out.txt', mode: str = 'text') -> None: ...
    def configure(self, **kwargs) -> None: ...

class Flatness(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class FlatnessDB(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class FlatnessSFX(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Flux(Algo):
    def __init__(self, halfRectify: bool = False, norm: str = 'L2') -> None: ...
    def configure(self, **kwargs) -> None: ...

class FrameBuffer(Algo):
    def __init__(self, bufferSize: int = 2048, zeroPadding: bool = True) -> None: ...
    def configure(self, **kwargs) -> None: ...

class FrameCutter(Algo):
    def __init__(self, frameSize: int = 1024, hopSize: int = 512, lastFrameToEndOfFile: bool = False, silentFrames: str = 'noise', startFromZero: bool = False, validFrameThresholdRatio: float = 0) -> None: ...
    def configure(self, **kwargs) -> None: ...

class FrameToReal(Algo):
    def __init__(self, frameSize: int = 2048, hopSize: int = 128) -> None: ...
    def configure(self, **kwargs) -> None: ...

class FrequencyBands(Algo):
    def __init__(self, frequencyBands: np.ndarray = '[0', sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class GFCC(Algo):
    def __init__(self, dctType: int = 2, highFrequencyBound: float = 22050, inputSize: int = 1025, logType: str = 'dbamp', lowFrequencyBound: float = 40, numberBands: int = 40, numberCoefficients: int = 13, sampleRate: float = 44100, silenceThreshold: float = 1e-10, type: str = 'power') -> None: ...
    def configure(self, **kwargs) -> None: ...

class GapsDetector(Algo):
    def __init__(self, attackTime: float = 0.05, frameSize: int = 2048, hopSize: int = 1024, kernelSize: int = 11, maximumTime: float = 3500, minimumTime: float = 10, postpowerTime: float = 40, prepowerThreshold: float = -30, prepowerTime: float = 40, releaseTime: float = 0.05, sampleRate: float = 44100, silenceThreshold: float = -50) -> None: ...
    def configure(self, **kwargs) -> None: ...

class GeometricMean(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class HFC(Algo):
    def __init__(self, sampleRate: float = 44100, type: str = 'Masri') -> None: ...
    def configure(self, **kwargs) -> None: ...

class HPCP(Algo):
    def __init__(self, bandPreset: bool = True, bandSplitFrequency: float = 500, harmonics: int = 0, maxFrequency: float = 5000, maxShifted: bool = False, minFrequency: float = 40, nonLinear: bool = False, normalized: str = 'unitMax', referenceFrequency: float = 440, sampleRate: float = 44100, size: int = 12, weightType: str = 'squaredCosine', windowSize: float = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class HarmonicBpm(Algo):
    def __init__(self, bpm: float = 60, threshold: float = 20, tolerance: float = 5) -> None: ...
    def configure(self, **kwargs) -> None: ...

class HarmonicMask(Algo):
    def __init__(self, attenuation: float = -200, binWidth: int = 4, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class HarmonicModelAnal(Algo):
    def __init__(self, freqDevOffset: float = 20, freqDevSlope: float = 0.01, harmDevSlope: float = 0.01, hopSize: int = 512, magnitudeThreshold: float = -74, maxFrequency: float = 5000, maxPeaks: int = 100, maxnSines: int = 100, minFrequency: float = 20, nHarmonics: int = 100, orderBy: str = 'frequency', sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class HarmonicPeaks(Algo):
    def __init__(self, maxHarmonics: int = 20, tolerance: float = 0.2) -> None: ...
    def configure(self, **kwargs) -> None: ...

class HighPass(Algo):
    def __init__(self, cutoffFrequency: float = 1500, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class HighResolutionFeatures(Algo):
    def __init__(self, maxPeaks: int = 24) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Histogram(Algo):
    def __init__(self, maxValue: float = 1, minValue: float = 0, normalize: str = 'none', numberBins: int = 10) -> None: ...
    def configure(self, **kwargs) -> None: ...

class HprModelAnal(Algo):
    def __init__(self, fftSize: int = 2048, freqDevOffset: int = 20, freqDevSlope: float = 0.01, harmDevSlope: float = 0.01, hopSize: int = 512, magnitudeThreshold: float = 0, maxFrequency: float = 5000, maxPeaks: int = 100, maxnSines: int = 100, minFrequency: float = 20, nHarmonics: int = 100, orderBy: str = 'frequency', sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def configure(self, **kwargs) -> None: ...

class HpsModelAnal(Algo):
    def __init__(self, fftSize: int = 2048, freqDevOffset: int = 20, freqDevSlope: float = 0.01, harmDevSlope: float = 0.01, hopSize: int = 512, magnitudeThreshold: float = 0, maxFrequency: float = 5000, maxPeaks: int = 100, maxnSines: int = 100, minFrequency: float = 20, nHarmonics: int = 100, orderBy: str = 'frequency', sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def configure(self, **kwargs) -> None: ...

class HumDetector(Algo):
    def __init__(self, Q0: float = 0.1, Q1: float = 0.55, detectionThreshold: float = 5, frameSize: float = 0.4, hopSize: float = 0.2, maximumFrequency: float = 400, minimumDuration: float = 0.5, minimumFrequency: float = 27.5, numberHarmonics: int = 1, sampleRate: float = 44100, timeContinuity: float = 10, timeWindow: float = 9) -> None: ...
    def configure(self, **kwargs) -> None: ...

class IDCT(Algo):
    def __init__(self, dctType: int = 2, inputSize: int = 10, liftering: int = 0, outputSize: int = 10) -> None: ...
    def configure(self, **kwargs) -> None: ...

class IFFT(Algo):
    def __init__(self, normalize: bool = True, size: int = 1024) -> None: ...
    def configure(self, **kwargs) -> None: ...

class IFFTC(Algo):
    def __init__(self, normalize: bool = True, size: int = 1024) -> None: ...
    def configure(self, **kwargs) -> None: ...

class IIR(Algo):
    def __init__(self, denominator: np.ndarray = '[1]', numerator: np.ndarray = '[1]') -> None: ...
    def configure(self, **kwargs) -> None: ...

class Inharmonicity(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class InstantPower(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Key(Algo):
    def __init__(self, averageDetuningCorrection: bool = True, numHarmonics: int = 4, pcpSize: int = 36, pcpThreshold: float = 0.2, profileType: str = 'bgate', slope: float = 0.6, useMajMin: bool = False, usePolyphony: bool = True, useThreeChords: bool = True) -> None: ...
    def configure(self, **kwargs) -> None: ...

class KeyExtractor(Algo):
    def __init__(self, averageDetuningCorrection: bool = True, frameSize: int = 4096, hopSize: int = 4096, hpcpSize: int = 12, maxFrequency: float = 3500, maximumSpectralPeaks: int = 60, minFrequency: float = 25, pcpThreshold: float = 0.2, profileType: str = 'bgate', sampleRate: float = 44100, spectralPeaksThreshold: float = 0.0001, tuningFrequency: float = 440, weightType: str = 'cosine', windowType: str = 'hann') -> None: ...
    def configure(self, **kwargs) -> None: ...

class LPC(Algo):
    def __init__(self, order: int = 10, sampleRate: float = 44100, type: str = 'regular') -> None: ...
    def configure(self, **kwargs) -> None: ...

class Larm(Algo):
    def __init__(self, attackTime: float = 10, power: float = 1.5, releaseTime: float = 1500, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Leq(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class LevelExtractor(Algo):
    def __init__(self, frameSize: int = 88200, hopSize: int = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class LogAttackTime(Algo):
    def __init__(self, sampleRate: float = 44100, startAttackThreshold: float = 0.2, stopAttackThreshold: float = 0.9) -> None: ...
    def configure(self, **kwargs) -> None: ...

class LogSpectrum(Algo):
    def __init__(self, binsPerSemitone: float = 3, frameSize: int = 1025, nOctave: int = 7, rollOn: float = 0, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class LoopBpmConfidence(Algo):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class LoopBpmEstimator(Algo):
    def __init__(self, confidenceThreshold: float = 0.95) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Loudness(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class LoudnessEBUR128(Algo):
    def __init__(self, hopSize: float = 0.1, sampleRate: float = 44100, startAtZero: bool = False) -> None: ...
    def configure(self, **kwargs) -> None: ...

class LoudnessEBUR128Filter(Algo):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class LoudnessVickers(Algo):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class LowLevelSpectralEqloudExtractor(Algo):
    def __init__(self, frameSize: int = 2048, hopSize: int = 1024, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class LowLevelSpectralExtractor(Algo):
    def __init__(self, frameSize: int = 2048, hopSize: int = 1024, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class LowPass(Algo):
    def __init__(self, cutoffFrequency: float = 1500, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class MFCC(Algo):
    def __init__(self, dctType: int = 2, highFrequencyBound: float = 11000, inputSize: int = 1025, liftering: int = 0, logType: str = 'dbamp', lowFrequencyBound: float = 0, normalize: str = 'unit_sum', numberBands: int = 40, numberCoefficients: int = 13, sampleRate: float = 44100, silenceThreshold: float = 1e-10, type: str = 'power', warpingFormula: str = 'htkMel', weighting: str = 'warping') -> None: ...
    def configure(self, **kwargs) -> None: ...

class Magnitude(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class MaxFilter(Algo):
    def __init__(self, causal: bool = True, width: int = 3) -> None: ...
    def configure(self, **kwargs) -> None: ...

class MaxMagFreq(Algo):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class MaxToTotal(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Mean(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Median(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class MedianFilter(Algo):
    def __init__(self, kernelSize: int = 11) -> None: ...
    def configure(self, **kwargs) -> None: ...

class MelBands(Algo):
    def __init__(self, highFrequencyBound: float = 22050, inputSize: int = 1025, log: bool = False, lowFrequencyBound: float = 0, normalize: str = 'unit_sum', numberBands: int = 24, sampleRate: float = 44100, type: str = 'power', warpingFormula: str = 'htkMel', weighting: str = 'warping') -> None: ...
    def configure(self, **kwargs) -> None: ...

class MetadataReader(Algo):
    def __init__(self, failOnError: bool = False, filename: str = '“”') -> None: ...
    def configure(self, **kwargs) -> None: ...

class Meter(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class MinMax(Algo):
    def __init__(self, type: str = 'min') -> None: ...
    def configure(self, **kwargs) -> None: ...

class MinToTotal(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class MonoLoader(Algo):
    def __init__(self, audioStream: int = 0, downmix: str = 'mix', filename: str, resampleQuality: int = 1, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class MonoMixer(Algo):
    def __init__(self, type: str = 'mix') -> None: ...
    def configure(self, **kwargs) -> None: ...

class MonoWriter(Algo):
    def __init__(self, bitrate: int = 192, filename: str, format: str = 'wav', sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class MovingAverage(Algo):
    def __init__(self, size: int = 6) -> None: ...
    def configure(self, **kwargs) -> None: ...

class MultiPitchMelodia(Algo):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, frameSize: int = 2048, guessUnvoiced: bool = False, harmonicWeight: float = 0.8, hopSize: int = 128, magnitudeCompression: float = 1, magnitudeThreshold: int = 40, maxFrequency: float = 20000, minDuration: int = 100, minFrequency: float = 80, numberHarmonics: int = 20, peakDistributionThreshold: float = 0.9, peakFrameThreshold: float = 0.9, pitchContinuity: float = 27.5625, referenceFrequency: float = 55, sampleRate: float = 44100, timeContinuity: int = 100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Multiplexer(Algo):
    def __init__(self, numberRealInputs: int = 0, numberVectorRealInputs: int = 0) -> None: ...
    def configure(self, **kwargs) -> None: ...

class NNLSChroma(Algo):
    def __init__(self, chromaNormalization: str = 'none', frameSize: int = 1025, sampleRate: float = 44100, spectralShape: float = 0.7, spectralWhitening: float = 1, tuningMode: str = 'global', useNNLS: bool = True) -> None: ...
    def configure(self, **kwargs) -> None: ...

class NSGConstantQ(Algo):
    def __init__(self, binsPerOctave: int = 48, gamma: int = 0, inputSize: int = 4096, maxFrequency: float = 7040, minFrequency: float = 27.5, minimumWindow: int = 4, normalize: str = 'none', phaseMode: str = 'global', rasterize: str = 'full', sampleRate: float = 44100, window: str = 'hannnsgcq', windowSizeFactor: int = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class NSGConstantQStreaming(Algo):
    def __init__(self, binsPerOctave: int = 48, gamma: int = 0, inputSize: int = 4096, maxFrequency: float = 7040, minFrequency: float = 27.5, minimumWindow: int = 4, normalize: str = 'none', phaseMode: str = 'global', rasterize: str = 'full', sampleRate: float = 44100, window: str = 'hannnsgcq', windowSizeFactor: int = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class NSGIConstantQ(Algo):
    def __init__(self, binsPerOctave: int = 48, gamma: int = 0, inputSize: int = 4096, maxFrequency: float = 7040, minFrequency: float = 27.5, minimumWindow: int = 4, normalize: str = 'none', phaseMode: str = 'global', rasterize: str = 'full', sampleRate: float = 44100, window: str = 'hannnsgcq', windowSizeFactor: int = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class NoiseAdder(Algo):
    def __init__(self, fixSeed: bool = False, level: int = -100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class NoiseBurstDetector(Algo):
    def __init__(self, alpha: float = 0.9, silenceThreshold: int = -50, threshold: int = 8) -> None: ...
    def configure(self, **kwargs) -> None: ...

class NoveltyCurve(Algo):
    def __init__(self, frameRate: float = 344.531, normalize: bool = False, weightCurve: np.ndarray = '[]', weightCurveType: str = 'inverse_quadratic') -> None: ...
    def configure(self, **kwargs) -> None: ...

class OddToEvenHarmonicEnergyRatio(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class OnsetDetection(Algo):
    def __init__(self, method: str = 'hfc', sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class OnsetDetectionGlobal(Algo):
    def __init__(self, frameSize: int = 2048, hopSize: int = 512, method: str = 'infogain', sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class OnsetRate(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Onsets(Algo):
    def __init__(self, alpha: float = 0.1, delay: int = 5, frameRate: float = 86.1328, silenceThreshold: float = 0.02) -> None: ...
    def configure(self, **kwargs) -> None: ...

class OverlapAdd(Algo):
    def __init__(self, frameSize: int = 2048, gain: float = 1, hopSize: int = 128) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Panning(Algo):
    def __init__(self, averageFrames: int = 43, numBands: int = 1, numCoeffs: int = 20, panningBins: int = 512, sampleRate: float = 44100, warpedPanorama: bool = True) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PeakDetection(Algo):
    def __init__(self, interpolate: bool = True, maxPeaks: int = 100, maxPosition: float = 1, minPeakDistance: float = 0, minPosition: float = 0, orderBy: str = 'position', range: float = 1, threshold: float = -1e+06) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PercivalBpmEstimator(Algo):
    def __init__(self, frameSize: int = 1024, frameSizeOSS: int = 2048, hopSize: int = 128, hopSizeOSS: int = 128, maxBPM: int = 210, minBPM: int = 50, sampleRate: int = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PercivalEnhanceHarmonics(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PercivalEvaluatePulseTrains(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchContours(Algo):
    def __init__(self, binResolution: float = 10, hopSize: int = 128, minDuration: float = 100, peakDistributionThreshold: float = 0.9, peakFrameThreshold: float = 0.9, pitchContinuity: float = 27.5625, sampleRate: float = 44100, timeContinuity: float = 100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchContoursMelody(Algo):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, guessUnvoiced: bool = False, hopSize: int = 128, maxFrequency: float = 20000, minFrequency: float = 80, referenceFrequency: float = 55, sampleRate: float = 44100, voiceVibrato: bool = False, voicingTolerance: float = 0.2) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchContoursMonoMelody(Algo):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, guessUnvoiced: bool = False, hopSize: int = 128, maxFrequency: float = 20000, minFrequency: float = 80, referenceFrequency: float = 55, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchContoursMultiMelody(Algo):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, guessUnvoiced: bool = False, hopSize: int = 128, maxFrequency: float = 20000, minFrequency: float = 80, referenceFrequency: float = 55, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchFilter(Algo):
    def __init__(self, confidenceThreshold: int = 36, minChunkSize: int = 30, useAbsolutePitchConfidence: bool = False) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchMelodia(Algo):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, frameSize: int = 2048, guessUnvoiced: bool = False, harmonicWeight: float = 0.8, hopSize: int = 128, magnitudeCompression: float = 1, magnitudeThreshold: int = 40, maxFrequency: float = 20000, minDuration: int = 100, minFrequency: float = 80, numberHarmonics: int = 20, peakDistributionThreshold: float = 0.9, peakFrameThreshold: float = 0.9, pitchContinuity: float = 27.5625, referenceFrequency: float = 55, sampleRate: float = 44100, timeContinuity: int = 100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchSalience(Algo):
    def __init__(self, highBoundary: float = 5000, lowBoundary: float = 100, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchSalienceFunction(Algo):
    def __init__(self, binResolution: float = 10, harmonicWeight: float = 0.8, magnitudeCompression: float = 1, magnitudeThreshold: float = 40, numberHarmonics: int = 20, referenceFrequency: float = 55) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchSalienceFunctionPeaks(Algo):
    def __init__(self, binResolution: float = 10, maxFrequency: float = 1760, minFrequency: float = 55, referenceFrequency: float = 55) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchYin(Algo):
    def __init__(self, frameSize: int = 2048, interpolate: bool = True, maxFrequency: float = 22050, minFrequency: float = 20, sampleRate: float = 44100, tolerance: float = 0.15) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchYinFFT(Algo):
    def __init__(self, frameSize: int = 2048, interpolate: bool = True, maxFrequency: float = 22050, minFrequency: float = 20, sampleRate: float = 44100, tolerance: float = 1, weighting: str = 'custom') -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchYinProbabilistic(Algo):
    def __init__(self, frameSize: int = 2048, hopSize: int = 256, lowRMSThreshold: float = 0.1, outputUnvoiced: str = 'negative', preciseTime: bool = False, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchYinProbabilities(Algo):
    def __init__(self, frameSize: int = 2048, lowAmp: float = 0.1, preciseTime: bool = False, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PitchYinProbabilitiesHMM(Algo):
    def __init__(self, minFrequency: float = 61.735, numberBinsPerSemitone: int = 5, selfTransition: float = 0.99, yinTrust: float = 0.5) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PolarToCartesian(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PoolAggregator(Algo):
    def __init__(self, defaultStats: list[str] = '[“mean”', exceptions: Any = '{}') -> None: ...
    def configure(self, **kwargs) -> None: ...

class PoolToTensor(Algo):
    def __init__(self, namespace: str = 'input_0') -> None: ...
    def configure(self, **kwargs) -> None: ...

class PowerMean(Algo):
    def __init__(self, power: float = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PowerSpectrum(Algo):
    def __init__(self, size: int = 2048) -> None: ...
    def configure(self, **kwargs) -> None: ...

class PredominantPitchMelodia(Algo):
    def __init__(self, binResolution: float = 10, filterIterations: int = 3, frameSize: int = 2048, guessUnvoiced: bool = False, harmonicWeight: float = 0.8, hopSize: int = 128, magnitudeCompression: float = 1, magnitudeThreshold: int = 40, maxFrequency: float = 20000, minDuration: int = 100, minFrequency: float = 80, numberHarmonics: int = 20, peakDistributionThreshold: float = 0.9, peakFrameThreshold: float = 0.9, pitchContinuity: float = 27.5625, referenceFrequency: float = 55, sampleRate: float = 44100, timeContinuity: int = 100, voiceVibrato: bool = False, voicingTolerance: float = 0.2) -> None: ...
    def configure(self, **kwargs) -> None: ...

class RMS(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class RawMoments(Algo):
    def __init__(self, range: float = 22050) -> None: ...
    def configure(self, **kwargs) -> None: ...

class RealAccumulator(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class ReplayGain(Algo):
    def __init__(self, applyEqloud: bool = True, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Resample(Algo):
    def __init__(self, inputSampleRate: float = 44100, outputSampleRate: float = 44100, quality: int = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class ResampleFFT(Algo):
    def __init__(self, inSize: int = 128, outSize: int = 128) -> None: ...
    def configure(self, **kwargs) -> None: ...

class RhythmDescriptors(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class RhythmExtractor(Algo):
    def __init__(self, frameHop: int = 1024, frameSize: int = 1024, hopSize: int = 256, lastBeatInterval: float = 0.1, maxTempo: int = 208, minTempo: int = 40, numberFrames: int = 1024, sampleRate: float = 44100, tempoHints: np.ndarray = '[]', tolerance: float = 0.24, useBands: bool = True, useOnset: bool = True) -> None: ...
    def configure(self, **kwargs) -> None: ...

class RhythmExtractor2013(Algo):
    def __init__(self, maxTempo: int = 208, method: str = 'multifeature', minTempo: int = 40) -> None: ...
    def configure(self, **kwargs) -> None: ...

class RhythmTransform(Algo):
    def __init__(self, frameSize: int = 256, hopSize: int = 32) -> None: ...
    def configure(self, **kwargs) -> None: ...

class RollOff(Algo):
    def __init__(self, cutoff: float = 0.85, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SBic(Algo):
    def __init__(self, cpw: float = 1.5, inc1: int = 60, inc2: int = 20, minLength: int = 10, size1: int = 300, size2: int = 200) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SNR(Algo):
    def __init__(self, MAAlpha: float = 0.95, MMSEAlpha: float = 0.98, NoiseAlpha: float = 0.9, frameSize: int = 512, noiseThreshold: float = -40, sampleRate: float = 44100, useBroadbadNoiseCorrection: bool = True) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SaturationDetector(Algo):
    def __init__(self, differentialThreshold: float = 0.001, energyThreshold: float = -1, frameSize: int = 512, hopSize: int = 256, minimumDuration: float = 0.005, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Scale(Algo):
    def __init__(self, clipping: bool = True, factor: float = 10, maxAbsValue: float = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SilenceRate(Algo):
    def __init__(self, thresholds: np.ndarray = '[]') -> None: ...
    def configure(self, **kwargs) -> None: ...

class SineModelAnal(Algo):
    def __init__(self, freqDevOffset: float = 20, freqDevSlope: float = 0.01, magnitudeThreshold: float = -74, maxFrequency: float = 22050, maxPeaks: int = 250, maxnSines: int = 100, minFrequency: float = 0, orderBy: str = 'frequency', sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SineModelSynth(Algo):
    def __init__(self, fftSize: int = 2048, hopSize: int = 512, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SineSubtraction(Algo):
    def __init__(self, fftSize: int = 512, hopSize: int = 128, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SingleBeatLoudness(Algo):
    def __init__(self, beatDuration: float = 0.05, beatWindowDuration: float = 0.1, frequencyBands: np.ndarray = '[0', onsetStart: str = 'sumEnergy', sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SingleGaussian(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Slicer(Algo):
    def __init__(self, endTimes: np.ndarray = '[]', sampleRate: float = 44100, startTimes: np.ndarray = '[]', timeUnits: str = 'seconds') -> None: ...
    def configure(self, **kwargs) -> None: ...

class SpectralCentroidTime(Algo):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SpectralComplexity(Algo):
    def __init__(self, magnitudeThreshold: float = 0.005, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SpectralContrast(Algo):
    def __init__(self, frameSize: int = 2048, highFrequencyBound: float = 11000, lowFrequencyBound: float = 20, neighbourRatio: float = 0.4, numberBands: int = 6, sampleRate: float = 22050, staticDistribution: float = 0.15) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SpectralPeaks(Algo):
    def __init__(self, magnitudeThreshold: float = 0, maxFrequency: float = 5000, maxPeaks: int = 100, minFrequency: float = 0, orderBy: str = 'frequency', sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SpectralWhitening(Algo):
    def __init__(self, maxFrequency: float = 5000, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Spectrum(Algo):
    def __init__(self, size: int = 2048) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SpectrumCQ(Algo):
    def __init__(self, binsPerOctave: int = 12, minFrequency: float = 32.7, minimumKernelSize: int = 4, numberBins: int = 84, sampleRate: float = 44100, scale: float = 1, threshold: float = 0.01, windowType: str = 'hann', zeroPhase: bool = True) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SpectrumToCent(Algo):
    def __init__(self, bands: int = 720, centBinResolution: float = 10, inputSize: int = 32768, log: bool = True, minimumFrequency: float = 164, normalize: str = 'unit_sum', sampleRate: float = 44100, type: str = 'power') -> None: ...
    def configure(self, **kwargs) -> None: ...

class Spline(Algo):
    def __init__(self, beta1: float = 1, beta2: float = 0, type: str = 'b', xPoints: np.ndarray = '[0', yPoints: np.ndarray = '[0') -> None: ...
    def configure(self, **kwargs) -> None: ...

class SprModelAnal(Algo):
    def __init__(self, fftSize: int = 2048, freqDevOffset: int = 20, freqDevSlope: float = 0.01, hopSize: int = 512, magnitudeThreshold: float = 0, maxFrequency: float = 5000, maxPeaks: int = 100, maxnSines: int = 100, minFrequency: float = 0, orderBy: str = 'frequency', sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SprModelSynth(Algo):
    def __init__(self, fftSize: int = 2048, hopSize: int = 512, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SpsModelAnal(Algo):
    def __init__(self, fftSize: int = 2048, freqDevOffset: int = 20, freqDevSlope: float = 0.01, hopSize: int = 512, magnitudeThreshold: float = 0, maxFrequency: float = 5000, maxPeaks: int = 100, maxnSines: int = 100, minFrequency: float = 0, orderBy: str = 'frequency', sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SpsModelSynth(Algo):
    def __init__(self, fftSize: int = 2048, hopSize: int = 512, sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def configure(self, **kwargs) -> None: ...

class StartStopCut(Algo):
    def __init__(self, frameSize: int = 256, hopSize: int = 256, maximumStartTime: float = 10, maximumStopTime: float = 10, sampleRate: float = 44100, threshold: int = -60) -> None: ...
    def configure(self, **kwargs) -> None: ...

class StartStopSilence(Algo):
    def __init__(self, threshold: int = -60) -> None: ...
    def configure(self, **kwargs) -> None: ...

class StereoDemuxer(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class StereoMuxer(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class StereoTrimmer(Algo):
    def __init__(self, endTime: float = 1e+06, sampleRate: float = 44100, startTime: float = 0) -> None: ...
    def configure(self, **kwargs) -> None: ...

class StochasticModelAnal(Algo):
    def __init__(self, fftSize: int = 2048, hopSize: int = 512, sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def configure(self, **kwargs) -> None: ...

class StochasticModelSynth(Algo):
    def __init__(self, fftSize: int = 2048, hopSize: int = 512, sampleRate: float = 44100, stocf: float = 0.2) -> None: ...
    def configure(self, **kwargs) -> None: ...

class StrongDecay(Algo):
    def __init__(self, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class StrongPeak(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SuperFluxExtractor(Algo):
    def __init__(self, combine: float = 20, frameSize: int = 2048, hopSize: int = 256, ratioThreshold: float = 16, sampleRate: float = 44100, threshold: float = 0.05) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SuperFluxNovelty(Algo):
    def __init__(self, binWidth: int = 3, frameWidth: int = 2) -> None: ...
    def configure(self, **kwargs) -> None: ...

class SuperFluxPeaks(Algo):
    def __init__(self, combine: float = 30, frameRate: float = 172, pre_avg: float = 100, pre_max: float = 30, ratioThreshold: float = 16, threshold: float = 0.05) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TCToTotal(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TempoScaleBands(Algo):
    def __init__(self, bandsGain: np.ndarray = '[2', frameTime: float = 512) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TempoTap(Algo):
    def __init__(self, frameHop: int = 1024, frameSize: int = 256, maxTempo: int = 208, minTempo: int = 40, numberFrames: int = 1024, sampleRate: float = 44100, tempoHints: np.ndarray = '[]') -> None: ...
    def configure(self, **kwargs) -> None: ...

class TempoTapDegara(Algo):
    def __init__(self, maxTempo: int = 208, minTempo: int = 40, resample: str = 'none', sampleRateODF: float = 86.1328) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TempoTapMaxAgreement(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TempoTapTicks(Algo):
    def __init__(self, frameHop: int = 512, hopSize: int = 256, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TensorNormalize(Algo):
    def __init__(self, axis: int = 0, scaler: str = 'standard', skipConstantSlices: bool = True) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TensorToPool(Algo):
    def __init__(self, mode: str = 'overwrite', namespace: str = 'input_0') -> None: ...
    def configure(self, **kwargs) -> None: ...

class TensorToVectorReal(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TensorTranspose(Algo):
    def __init__(self, permutation: Any) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TensorflowInputFSDSINet(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TensorflowInputMusiCNN(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TensorflowInputTempoCNN(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TensorflowInputVGGish(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TonalExtractor(Algo):
    def __init__(self, frameSize: int = 4096, hopSize: int = 2048, tuningFrequency: float = 440) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TriangularBands(Algo):
    def __init__(self, frequencyBands: np.ndarray = '[21.533203125', inputSize: int = 1025, log: bool = True, normalize: str = 'unit_sum', sampleRate: float = 44100, type: str = 'power', weighting: str = 'linear') -> None: ...
    def configure(self, **kwargs) -> None: ...

class TriangularBarkBands(Algo):
    def __init__(self, highFrequencyBound: float = 22050, inputSize: int = 1025, log: bool = False, lowFrequencyBound: float = 0, normalize: str = 'unit_sum', numberBands: int = 24, sampleRate: float = 44100, type: str = 'power', weighting: str = 'warping') -> None: ...
    def configure(self, **kwargs) -> None: ...

class Trimmer(Algo):
    def __init__(self, endTime: float = 1e+06, sampleRate: float = 44100, startTime: float = 0) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Tristimulus(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TruePeakDetector(Algo):
    def __init__(self, blockDC: bool = False, emphasise: bool = False, oversamplingFactor: int = 4, quality: int = 1, sampleRate: float = 44100, threshold: float = -0.0002, version: int = 4) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TuningFrequency(Algo):
    def __init__(self, resolution: float = 1) -> None: ...
    def configure(self, **kwargs) -> None: ...

class TuningFrequencyExtractor(Algo):
    def __init__(self, frameSize: int = 4096, hopSize: int = 2048) -> None: ...
    def configure(self, **kwargs) -> None: ...

class UnaryOperator(Algo):
    def __init__(self, scale: float = 1, shift: float = 0, type: str = 'identity') -> None: ...
    def configure(self, **kwargs) -> None: ...

class UnaryOperatorStream(Algo):
    def __init__(self, scale: float = 1, shift: float = 0, type: str = 'identity') -> None: ...
    def configure(self, **kwargs) -> None: ...

class Variance(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class VectorRealAccumulator(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class VectorRealToTensor(Algo):
    def __init__(self, batchHopSize: int = 0, lastBatchMode: str = 'push', lastPatchMode: str = 'repeat', patchHopSize: int = 0, shape: Any = '[1') -> None: ...
    def configure(self, **kwargs) -> None: ...

class Vibrato(Algo):
    def __init__(self, maxExtend: float = 250, maxFrequency: float = 8, minExtend: float = 50, minFrequency: float = 4, sampleRate: float = 344.531) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Viterbi(Algo):
    def __init__(self) -> None: ...
    def configure(self, **kwargs) -> None: ...

class WarpedAutoCorrelation(Algo):
    def __init__(self, maxLag: int = 1, sampleRate: float = 44100) -> None: ...
    def configure(self, **kwargs) -> None: ...

class Welch(Algo):
    def __init__(self, averagingFrames: int = 10, fftSize: int = 1024, frameSize: int = 512, sampleRate: float = 44100, scaling: str = 'density', windowType: str = 'hann') -> None: ...
    def configure(self, **kwargs) -> None: ...

class Windowing(Algo):
    def __init__(self, constantsDecimals: int = 5, normalized: bool = True, size: int = 1024, splitPadding: bool = False, symmetric: bool = True, type: str = 'hann', zeroPadding: int = 0, zeroPhase: bool = True) -> None: ...
    def configure(self, **kwargs) -> None: ...

class ZeroCrossingRate(Algo):
    def __init__(self, threshold: float = 0) -> None: ...
    def configure(self, **kwargs) -> None: ...
